[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
	-Iinclude

lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.9
	adafruit/Adafruit GFX Library@^1.11.9
	Chris--A/Keypad@^3.1.1
	jrowberg/I2Cdevlib-MPU6050@^1.0.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	blynkkk/BlynkNcpDriver@^0.7.0

lib_extra_dirs = lib