
[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    Chris--A/Keypad@^3.1.1
    jrowberg/I2Cdevlib-MPU6050@^1.0.0
    adafruit/Adafruit Unified Sensor@^1.1.15

lib_ldf_mode = deep+
lib_ldf_verbose = 1
lib_extra_dirs = lib

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_FREERTOS_UNICORE=0
    -O2
    -Iinclude
    -Ilib
    -Ilib/Calibration
    -Ilib/MotorDrive
    -Ilib/Safety
    -Ilib/Sensors

board_build.partitions = default.csv
